package TestCase_SatLotto;


/// This Test Scenario covers Test cases involved with 
/// CREATE YOUR OWN LOTTO TICKETS STANDARD OPTION :
//1. Navigating to the Saturday Lotto via the Play Menu in the NavBar
//2. Selecting the default Standard Saturday Lotto Ticket option 
//3. Selecting an option from the dropdown NOTE: Testing can be done for all options and boundary values using a database and looping.
//4. Filling Ticket numbers one by one and by Using the FAST Fill option.
//5. FAST FILL AND CLEAR ALL BUTTONS tested in various combinations
//6. Navigate to the Checkout page via the Cart link Click
//7. Use Assert functionality to test the tickets labels total amount on Checkout page.
//8. Test the Empty Cart functionality.

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.junit.runner.Result;
public class TestCaseSatLottoCustomiseToCartTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
public static void main(String args[]) {
	  JUnitCore junit = new JUnitCore();
	  junit.addListener(new TextListener(System.out));
	  Result result = junit.run(TestCaseSatLottoCustomiseToCartTest.class); 
	  if (result.getFailureCount() > 0) {
	    System.out.println("Test Failed.");
	    System.exit(1);
	  } else {
	    System.out.println("Test Passed.");
	    System.exit(0);
	  }
	}
@Before
public void setUp() {
 System.setProperty("webdriver.chrome.driver","C:\\Users\\richa\\Downloads\\chromedriver_win32\\chromedriver.exe");
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void testCaseSatLottoCustomiseToCart() {
 driver.get("https://www.thelott.com//");
 driver.manage().window().setSize(new Dimension(1382, 886));
 driver.findElement(By.cssSelector(".ico-UiAngleDwn")).click();
 driver.findElement(By.cssSelector(".xsmall-collapse:nth-child(4)")).click();
 driver.findElement(By.id("playmenu")).click();
 driver.findElement(By.id("saturday-gold-lotto-tile")).click();
 driver.findElement(By.cssSelector(".marked-entry-title")).click();
 driver.findElement(By.cssSelector(".select > .au-target")).click();
 {
   WebElement dropdown = driver.findElement(By.cssSelector(".select > .au-target"));
   dropdown.findElement(By.xpath("//option[. = '4 Games - $3.30']")).click();
 }
 driver.findElement(By.cssSelector(".fast-select > span")).click();
 driver.findElement(By.cssSelector(".small-small-down > .ico-DsDelete")).click();
 driver.findElement(By.cssSelector(".tatts-enter > .au-target > .au-target:nth-child(2)")).click();
 driver.findElement(By.cssSelector(".tatts-enter .au-target:nth-child(46)")).click();
 driver.findElement(By.cssSelector(".tatts-enter .au-target:nth-child(10)")).click();
 driver.findElement(By.cssSelector(".tatts-enter .au-target:nth-child(38)")).click();
 driver.findElement(By.cssSelector(".tatts-enter .au-target:nth-child(24)")).click();
 driver.findElement(By.cssSelector(".tatts-enter .au-target:nth-child(25)")).click();
 driver.findElement(By.cssSelector(".au-target:nth-child(2) > .marked-entry-selection .buttons:nth-child(4) .ico-DsFastSelect")).click();
 driver.findElement(By.cssSelector(".active > .number-grid-container .au-target:nth-child(2)")).click();
 driver.findElement(By.cssSelector(".active .au-target:nth-child(11)")).click();
 driver.findElement(By.cssSelector(".active .au-target:nth-child(20)")).click();
 driver.findElement(By.cssSelector(".active .au-target:nth-child(29)")).click();
 driver.findElement(By.cssSelector(".active .au-target:nth-child(38)")).click();
 driver.findElement(By.cssSelector(".active .au-target:nth-child(10)")).click();
 driver.findElement(By.cssSelector(".au-target:nth-child(4) .buttons:nth-child(4) .ico-DsFastSelect")).click();
 driver.findElement(By.cssSelector(".clear > span")).click();
 driver.findElement(By.cssSelector(".au-target:nth-child(1) > .marked-entry-selection .buttons:nth-child(4) .ico-DsDelete")).click();
 driver.findElement(By.cssSelector(".au-target:nth-child(1) > .marked-entry-selection .buttons:nth-child(4) > .button:nth-child(1)")).click();
 driver.findElement(By.cssSelector(".active .medium-up-only > .clear")).click();
 driver.findElement(By.cssSelector(".au-target:nth-child(2) > .marked-entry-selection .buttons:nth-child(4) .ico-DsFastSelect")).click();
 driver.findElement(By.cssSelector(".au-target:nth-child(3) > .marked-entry-selection .buttons:nth-child(4) .ico-DsFastSelect")).click();
 driver.findElement(By.cssSelector(".active .medium-up-only > .fast-select")).click();
 driver.findElement(By.cssSelector(".au-target:nth-child(4) .numbers")).click();
 driver.findElement(By.cssSelector(".au-target > label")).click();
 driver.findElement(By.cssSelector(".multi-draw-select > .au-target:nth-child(1)")).click();
 {
   WebElement dropdown = driver.findElement(By.cssSelector(".multi-draw-select > .au-target:nth-child(1)"));
   dropdown.findElement(By.xpath("//option[. = '3 draws - $9.90']")).click();
 }
 driver.findElement(By.cssSelector(".au-target:nth-child(4) > .text:nth-child(1)")).click();
 assertThat(driver.findElement(By.cssSelector(".au-target:nth-child(4) > .text:nth-child(1)")).getText(), is("4 Game Standard entry"));
 driver.findElement(By.cssSelector(".au-target > .text:nth-child(2)")).click();
 assertThat(driver.findElement(By.cssSelector(".au-target > .text:nth-child(2)")).getText(), is("3 Draws"));
 driver.findElement(By.cssSelector(".price")).click();
 assertThat(driver.findElement(By.cssSelector(".price")).getText(), is("$9.90"));
 driver.findElement(By.cssSelector(".cart-button:nth-child(2)")).click();
 driver.findElement(By.cssSelector(".ico-DsCart")).click();
 driver.findElement(By.cssSelector(".align-center > .columns")).click();
 assertThat(driver.findElement(By.cssSelector(".lerv-offer-details > .text")).getText(), is("1 Ticket subtotal"));
 driver.findElement(By.cssSelector(".lerv-offer-details > .amount")).click();
 assertThat(driver.findElement(By.cssSelector(".lerv-offer-details > .amount")).getText(), is("$9.90"));
 driver.findElement(By.cssSelector(".purchase-button-container > .au-target > .au-target")).click();
 driver.findElement(By.cssSelector("use:nth-child(2)")).click();
 driver.findElement(By.linkText("Empty Cart")).click();
 driver.findElement(By.cssSelector(".button:nth-child(2)")).click();
}
}
